@echo off
echo Starting FastAPI Backend...
start "Backend Server" cmd /k "cd ..\fastapi_with_db-main && python main.py"

echo Starting React Frontend...
start "Frontend Server" cmd /k "cd my-project && npm run dev"

echo Both servers are starting...
